import { AppDefinition } from '../types';

export const APPS: Record<string, AppDefinition> = {
  chat: {
    id: 'chat',
    name: 'Realtime Chat',
    icon: 'MessageSquare',
    description: 'Chat in realtime with teammates and proactive agents.',
    color: '#6c5ce7',
    defaultWidth: 800,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 300,
    pinToTaskbar: true,
    category: 'core'
  },
  orbit: {
    id: 'orbit',
    name: 'Orbit Agent',
    icon: 'Compass',
    description: 'Your sarcastic proactive team assistant and memory manager.',
    color: '#00cec9',
    defaultWidth: 700,
    defaultHeight: 500,
    minWidth: 350,
    minHeight: 250,
    pinToTaskbar: true,
    category: 'agents'
  },
  icebound: {
    id: 'icebound',
    name: 'Icebound Agent',
    icon: 'Flame',
    description: 'The agent of chaos, sarcasm, and real talks.',
    color: '#fd79a8',
    defaultWidth: 700,
    defaultHeight: 500,
    minWidth: 350,
    minHeight: 250,
    pinToTaskbar: true,
    category: 'agents'
  },
  studio: {
    id: 'studio',
    name: 'Agent Studio',
    icon: 'Cpu',
    description: 'Build, wire, and test custom agent personas and tools.',
    color: '#fdcb6e',
    defaultWidth: 900,
    defaultHeight: 650,
    minWidth: 500,
    minHeight: 400,
    pinToTaskbar: true,
    category: 'tools'
  },
  marketplace: {
    id: 'marketplace',
    name: 'Plugin Store',
    icon: 'ShoppingBag',
    description: 'Discover and install plugins to extend your OS environment.',
    color: '#55efc4',
    defaultWidth: 850,
    defaultHeight: 600,
    minWidth: 450,
    minHeight: 350,
    pinToTaskbar: false,
    category: 'tools'
  },
  hackathons: {
    id: 'hackathons',
    name: 'Hackathon Finder',
    icon: 'Trophy',
    description: 'Discover, track, and get summarized insights on upcoming hackathons.',
    color: '#e84393',
    defaultWidth: 800,
    defaultHeight: 550,
    minWidth: 400,
    minHeight: 300,
    pinToTaskbar: false,
    category: 'tools'
  },
  files: {
    id: 'files',
    name: 'Obsidian Brain',
    icon: 'FolderOpen',
    description: 'Explore and read note summaries directly from your second brain.',
    color: '#ffeaa7',
    defaultWidth: 750,
    defaultHeight: 550,
    minWidth: 400,
    minHeight: 300,
    pinToTaskbar: true,
    category: 'core'
  },
  admin: {
    id: 'admin',
    name: 'Admin Panel',
    icon: 'Shield',
    description: 'Manage users, approvals, logs, and workspace policies.',
    color: '#d63031',
    defaultWidth: 900,
    defaultHeight: 600,
    minWidth: 500,
    minHeight: 400,
    pinToTaskbar: false,
    category: 'system'
  },
  settings: {
    id: 'settings',
    name: 'Settings',
    icon: 'Settings',
    description: 'Change your wallpaper, UI preferences, and agent configurations.',
    color: '#a0a0b8',
    defaultWidth: 600,
    defaultHeight: 450,
    minWidth: 350,
    minHeight: 250,
    pinToTaskbar: false,
    category: 'system'
  },
  search: {
    id: 'search',
    name: 'OmniSearch',
    icon: 'Search',
    description: 'Global hybrid search across chats, notes, decisions, and files.',
    color: '#0984e3',
    defaultWidth: 700,
    defaultHeight: 450,
    minWidth: 400,
    minHeight: 300,
    pinToTaskbar: false,
    category: 'system'
  }
};
