apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: unhinged-backend-pdb
  namespace: unhinged
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: unhinged-backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: unhinged-frontend-pdb
  namespace: unhinged
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: unhinged-frontend