apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unhinged-vault-pvc
  namespace: unhinged
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unhinged-export-pvc
  namespace: unhinged
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard